src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $town;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="datetime")
     */
    private $birthday;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $occupation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=Room::class, mappedBy="user")
     */
    private $rooms;

    public function __construct()
    {
        $this->rooms = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getTown(): ?string
    {
        return $this->town;
    }

    public function setTown(string $town): self
    {
        $this->town = $town;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getOccupation(): ?string
    {
        return $this->occupation;
    }

    public function setOccupation(string $occupation): self
    {
        $this->occupation = $occupation;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|Room[]
     */
    public function getRooms(): Collection
    {
        return $this->rooms;
    }

    public function addRoom(Room $room): self
    {
        if (!$this->rooms->contains($room)) {
            $this->rooms[] = $room;
            $room->setUser($this);
        }

        return $this;
    }

    public function removeRoom(Room $room): self
    {
        if ($this->rooms->removeElement($room)) {
            // set the owning side to null (unless already changed)
            if ($room->getUser() === $this) {
                $room->setUser(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block javascripts %}
            {# Les 3 prochains tags sont pour le nav bar #}
            <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
            {#  <script src="{{ asset('') }}"></script>#}

            {# Les 2 prochains tags sont pour le tableau #}
            <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
            <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
            

        {% endblock %}

        {% block stylesheets %}
            {# Les 2 prochains tags sont pour le nav bar #}
            <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
            {#<link href="{{ asset('css/navBar.css')}}" rel="stylesheet">#}

            {# Les 2 prochains tags sont pour le tableau #}
            <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
            {#<link href="{{ asset('css/table.css')}}" rel="stylesheet">#}
        {% endblock %}
    </head>
    <body>
        {% block body %}
            {% block head %}
                <div class="top bg-dark text-light py-3">
                    <div class="container-nav topheader">
                        <div class="d-flex justify-content-between">
                            <div class="left">
                                <a class="text-light logo lead" terget="_blank" href="https://www.totoprayogo.com">Logo</a>
                            </div>
                            <div class="kanan">
                                <a class="text-light logo lead" terget="_blank" href="https://github.com/doric">Click</a>
                            </div>
                        </div>
                    </div>
                </div>
    
                <div class="bottom bg-light sticky-top shadow-sm">
                    <div class="container-nav">
                        <ul class="nav nav-bottom nav-fill">
                            <li class="nav-item">
                                <a class="nav-link bg-primary text-white" terget="_blank" href="https://www.totoprayogo.com"><i class="fas fa-user-circle"></i> <span class="d-none d-sm-inline-block d-md-inline-block">People</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" terget="_blank" href="https://www.totoprayogo.com"><i class="fas fa-file-invoice"></i> <span class="d-none d-sm-inline-block d-md-inline-block">Project</span></a>
                            </li>
                
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="{{ path('create_room') }}"><i class="fas fa-plus-circle"></i> <span class="d-none d-sm-inline-block d-md-inline-block">Create a room</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#"><span class="badge badge-danger badge-pill custom-badge">20</span> <i class="fas fa-bell"></i> <span class="d-none d-sm-inline-block d-md-inline-block">Notification</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#"><i class="fas fa-cog"></i> <span class="d-none d-sm-inline-block d-md-inline-block">Setting</span></a>
                            </li>
                        </ul>

                    </div>
                </div>
            {% endblock %}
            {% block content %}

            {% endblock %}
        {% endblock %}
    </body>
</html>

templates/create.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <h1>{{test.id}}</h1>
{% endblock %}

templates/test.html.twig
{% for single in test %}
      <p>La personne qui à l'id {{single.id}} s'appelle {{single.firstName}} et habite à l'adresse {{single.address}}.</p>
{% endfor %}

templates/user_room.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <div class="container">
      <div class="row col-md-6 col-md-offset-2 custyle">
      <table class="table table-striped custab">
       <thead text-align="center">
       <tr>
             <th>Article: {{ room.article }}</th>
        </tr>
       </thead>
        <tr>
             <td> ID </td>
             <td> {{ room.id }} </td>
         </tr>
         <tr>
             <td> Prix </td> 
             <td> {{ room.prix }} </td>
         </tr>
         <tr>
             <td> Description </td>
             <td> {{ room.description }} </td>
         </tr>
         <tr>
             <td> Counter </td>
             <td> {{ room.counter }} </td>
         </tr>
         <td> Timer </td>
             <td> {{ room.timer }} </td>
         <tr>
             <td> Membres </td>
             <td><ul> {% for member in members %}  <li>{{ member.name }}</li>  {% endfor %} </ul></td>
         </tr>
         <tr>
             <td> Images </td>
             <td>
               {% for image in images %}  
                 <img src="{{image.BlobFile}}" alt="" width="100" height="100" /> 
               {% endfor %} 
               
             </td>
         </tr>
      </table>
      </div>
    </div>
   
{% endblock %}

templates/user_rooms.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <div class="container">
      <div class="row col-md-6 col-md-offset-2 custyle">
      <table class="table table-striped custab">
       <thead>
       <tr>
             <th>Name: {{ user.firstName }}</th>
         </tr>
        <tr>
            <th>Room ID</th>
            <th>Article</th>
        </tr>
       </thead>
        {% for room in rooms %}
        <tr>
            <td>{{ room.id }}</td>
            <td><a href="{{ path('show_room', { 'id': room.id } ) }}"> {{ room.article }}</a></td> 
            {# 'path' prend en paramètre le lien et les données qu'on veut envoyer dans le lien #}
        </tr>
        {% endfor %}
      </table>
      </div>
    </div>
{% endblock %}